name: Run Traffic Analysis

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  push:
    branches:
      - main

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests ipwhois pandas geopandas matplotlib

    - name: Run Traffic Analysis Script
      run: python benchmark_traffic_analysis.py

    - name: Commit and Push Results
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add output/
        git commit -m "Add traffic analysis results" || echo "No changes to commit"
        git push