name: Run Traffic Analysis

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - '.github/workflows/run_analysis.yml'

permissions:
  contents: write

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y traceroute dnsutils

    - name: Install Python dependencies
      run: |
        pip install requests ipwhois matplotlib geopandas pandas plotly

    - name: Cache Generated Outputs
      id: cache-results
      uses: actions/cache@v4
      with:
        path: output/
        key: ${{ runner.os }}-output-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-output-

    - name: Run Traffic Analysis Script
      if: steps.cache-results.outputs.cache-hit != 'true'
      run: python benchmark_traffic_analysis.py

    - name: Generate Visualization README
      run: |
        mkdir -p visualizations
        echo "# Government of Canada Traffic Analysis Visualizations" > visualizations/README.md
        echo "This report provides insights into traffic flows between Government of Canada networks and external platforms." >> visualizations/README.md
        echo "" >> visualizations/README.md
        echo "![WHOIS Choropleth Map](../output/whois_choropleth_map.png)" >> visualizations/README.md

    - name: Commit and Push Results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add output/ visualizations/README.md
        git rm -f output/bgp_routes_AS399188.json        
        git commit -m "Add traffic analysis visualizations" || echo "No changes to commit"
        git push
