name: Run Traffic Analysis

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    paths:
      - '.github/workflows/run_analysis.yml'  # Trigger only when this file is updated

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y traceroute dnsutils  # Install traceroute and dig for DNS

    - name: Install Python dependencies
      run: |
        pip install requests ipwhois matplotlib geopandas pandas

    - name: Run Traffic Analysis Script
      run: python benchmark_traffic_analysis.py

    - name: Commit and Push Results
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add output/
        git commit -m "Add traffic analysis results" || echo "No changes to commit"
        git push
